### ISSUE TITLE
BLM Vulnerability 

### ISSUE THREAD

**Issue by cypr00** [MathiasReker/blmvuln#1]
Hi,

I have' just used your BLM Module. All has gone well but there is one file it says maybe infected but when running clean it does not fix it.

The file is .............
The following files looks infected. They will be restored or removed by running the cleaning process:
docker-compose.yml

Is this something i can fix or need to be worried about ?

Many thanks in advance.

cypr00

**Comment by MathiasReker** [comment]
Hello @cypr00 

Thank you.

Can you try the new version and tell if you can still reproduce the bug?

Latest version: https://github.com/MathiasReker/blmvuln/releases/latest

**Comment by cypr00** [comment]
Hi Mathias,

Many thanks ! That has worked.

One other problem i have found, i receive the below list of file/folder permissions that are insecure and need changing. i run the cleaner and it shows as fixed. I have closed the app and when re opening the app the same files are back again.

The following file/folder permissions is insecure. They will be fixed by running the cleaning process:

**Comment by HartLarsson** [comment]
I've the same problem and folder are all 0755 permission that is allowed:

`    /**
     * Allowed folder permissions.
     *
     * @var string[]
     */
    const ALLOWED_FOLDER_PERMISSIONS = [
        '0755',
        '0750'
    ];`

**Comment by MathiasReker** [comment]
Hello

This issue is fixed in v. 2.1.2 :-)

**Comment by cypr00** [comment]
Thanks and great work
