### ISSUE TITLE
Issues with the module

### ISSUE THREAD

**Issue by Herman-Zernina** [MathiasReker/blmvuln#10]
HeyMathiasReker, thanks for the module. I've installed it got two issues:

1. It shows me the volnurability of the files which I cannot find on FTP. For example - themes/default/img/process-icon-save-and-stay.png while I don't have a degault theme in the themes folder. 

2. When I hit the 'run the cleaning process' button - nothing happens. 

 

Thanks!

**Comment by MathiasReker** [comment]
Hi @Herman-Zernina 

This seems strange. Can you share some screenshots? Don't include the URL in the screenshot, as it contains the link to your backoffice.

**Comment by Herman-Zernina** [comment]
Thanks for your response. I changed the rights to folders (755) and files (644) via SSH and then it became green in the module.

**Comment by MathiasReker** [comment]
Seems to be the issue that the server did not allow php to use chmod.
