### ISSUE TITLE
CRON task

### ISSUE THREAD

**Issue by benmariegas** [MathiasReker/blmvuln#12]
Hello, is it possible to set up a CRON task?
thank you

**Comment by MathiasReker** [comment]
Hello @benmariegas 

This is not possible at the moment. Why would you like to set up a cronjob? 🙂

**Comment by benmariegas** [comment]
thank you.
thanks to your module, the problem is corrected and I thank you. unfortunately after a few days the malicious code returns

**Comment by benmariegas** [comment]
by setting up a cron job, the cleaning process could be done faster.
I bought your security pro module but a priori, that is not enough to eradicate the malicious code that comes back

**Comment by MathiasReker** [comment]
I hold the belief that addressing the security vulnerability directly is the most appropriate course of action. Merely removing malware at fixed intervals would not provide a sustainable solution in the long run.

**Comment by benmariegas** [comment]
I totally agree with you but so far I haven't found where it comes from. Some settings of your security pro module can do it?

**Comment by MathiasReker** [comment]
The firewall log of security pro might help. Also have a look at the access log of your server.
