### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PatriceVigier** [MathiasReker/blmvuln#13]
PS 1.7.8.9
PHP 7.3

ContextErrorException
in [modules/blmvuln/src/domain/service/scanner/FilePermissions.php](https://xxxxx/admin/index.php/_profiler/open?_token=TUU_lMm76vYpKlELOLjHqB33aB2JojKeN9R9ySb_Kx4?file=modules/blmvuln/src/domain/service/scanner/FilePermissions.php&line=105#line105) (line 105)

            if (empty($this->insecurePermissionFiles)) {
                return false;
            }
            foreach ($this->insecurePermissionFiles as $path) {
                chmod($path, is_dir($path) ? Config::DEFAULT_MODE_FOLDER : Config::DEFAULT_MODE_FILES);
            }
            return true;
        }

**it cannot change the file or folder permission**

stack trace
<html><body>
<h3 class="trace-class">ContextErrorException
                    <span class="icon icon-close"><svg width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"></svg>
</span></h3>

 
--
Symfony\Component\Debug\Exception\ContextErrorException: Warning: chmod(): Operation not permitted    at modules/blmvuln/src/domain/service/scanner/FilePermissions.php:105   at PrestaShop\Module\BlmVuln\domain\service\scanner\FilePermissions->fix()      (modules/blmvuln/controllers/admin/AdminBlmVulnController.php:74)   at AdminBlmVulnController->fixVulnerabilities()      (modules/blmvuln/controllers/admin/AdminBlmVulnController.php:41)   at AdminBlmVulnController->renderList()      (classes/controller/AdminController.php:2211)   at AdminControllerCore->initContent()      (classes/controller/Controller.php:306)   at ControllerCore->run()      (classes/Dispatcher.php:525)   at DispatcherCore->dispatch()      (zadmin/index.php:93)

</body>
</html>

**Comment by MathiasReker** [comment]
The problem is that your server does not allow php to use chmod()

**Comment by PatriceVigier** [comment]
Hello,
**Thank you** for your answer
It is what I thought and there is  nothing I can do excepted to open writing to anyone, which will be a security problem!
Sincerely
