### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by dicremax** [MathiasReker/blmvuln#14]
il modulo BLM vulnerability funziona, ma contrariamente a quanto ho letto anche la versione più recente di Prestashop è affetta da questa vulnerabilità. Ho aggiornato il sito da 1 settimana e non è cambiato nulla, SQL injection tutti i giorni.
Servirebbe un cron job che lancia l'esecuzione del modulo almeno ogni 30 minuti.
Grazie.

**Comment by MathiasReker** [comment]
Hello. Sorry, but there will not be sutch feature.
