### ISSUE TITLE
Side admin menu entry

### ISSUE THREAD

**Issue by Kolar94** [MathiasReker/blmvuln#2]
The module left multiple entries in side admin menu. Take a look on the screenshot (one per module installation).
Presta 1.6.1.24

![blm](https://user-images.githubusercontent.com/45670575/181111129-a1c46136-cf1c-4075-bd8c-a782c911d826.JPG)

**Comment by MathiasReker** [comment]
Hello @Kolar94 

From v. 2.1.2, the menu link is no more added.

**Comment by MathiasReker** [comment]
Hello @Kolar94 

There is a workaround described in this issue: https://github.com/MathiasReker/blmvuln/issues/4
