### ISSUE TITLE
Controller has not been found...

### ISSUE THREAD

**Issue by KapriQ** [MathiasReker/blmvuln#3]
Thanks for the module, i have installed it in 1.6.1.17 and after opening the module i got error msg. 

**Controller has not been found...**

Error log is clean.

**Comment by MathiasReker** [comment]
Hello

Can you show me a screenshot?

**Comment by MathiasReker** [comment]
I can reproduce the issue. I will fix it.

**Comment by KapriQ** [comment]
![Screenshot from 2022-07-27 10-35-03](https://user-images.githubusercontent.com/31235411/181201737-957d37d2-0e65-4e92-b4d0-36b20593b0e7.png)

**Comment by MathiasReker** [comment]
Fixed in latest version: https://github.com/MathiasReker/blmvuln/releases/latest

**Comment by KapriQ** [comment]
Thanks, working :)
