### ISSUE TITLE
No "Run the cleaning process" button

### ISSUE THREAD

**Issue by Inovyou06** [MathiasReker/blmvuln#5]
Hello @MathiasReker 

Thank you for this module.

And after installation, I can't find the "Run the cleaning process" button, so I can't run it.

**Comment by MathiasReker** [comment]
Hello @Inovyou06 

It's the blue button in the downright corner.

![image](https://user-images.githubusercontent.com/26626066/181328337-f6eaf56d-e023-40d3-a29e-c34dde0dcbc7.png)

If you don't see it, please show me a screenshot of what you see.
