### ISSUE TITLE
Your module ricognized from codguard as malware

### ISSUE THREAD

**Issue by pianetasvapo** [MathiasReker/blmvuln#6]
Hi after installing your module i've got a message from codeguard that it was a malware! What can i do? 

Unfortunately, following a recent backup we detected malware on your site on Thursday, July 28, 2022.

If you're running a CMS like Wordpress, Joomla or Drupal, you should restore your data prior to the latest backup date when malware was identified so you can have your website running up again. After restoring your data, please update it to the latest version and update everything related to it like themes, plugins, modules, libraries and such. If there are any websites running on the same hosting account, please update them as well.

Also, we strongly recommend you change all your passwords for FTP/SFTP and shell access.

If you're running a custom system or you would like additional information, please take a look at our [Support Center]
Below is the malware report we generated:

{HEX}php.malware.magento.582 : home/....../public_html/modules/blmvuln/bin/[1.7.3.3/classes/module/Module.php](http://1.7.3.3/classes/module/Module.php)
{HEX}php.malware.magento.585 : home/------/public_html/modules/blmvuln/src/resources/config/Config.php

**Comment by MathiasReker** [comment]
Hello @pianetasvapo 

The reports from codeguard are false positives.

`{HEX}php.malware.magento.582 : home/....../public_html/modules/blmvuln/bin/[1.7.3.3/classes/module/Module.php](http://1.7.3.3/classes/module/Module.php)
`
This is a original file from PrestaShop 1.7.3.3. If I remove this file from the software package the module will no longer be compatible with PrestaShop 1.7.3.3.

`{HEX}php.malware.magento.585 : home/------/public_html/modules/blmvuln/src/resources/config/Config.php`
This file includes payloads to find the malware: https://github.com/MathiasReker/blmvuln/blob/develop/src/resources/config/Config.php#L170
If these are removed, the module will no longer be able to find it.

You can uninstall the module after running it once, but these warnings cannot be fixed.

**Comment by pianetasvapo** [comment]
Thanks MathiasReker/blmvuln,
I was sure of it but I wanted confirmation from you. What do you advise me
to do? Can codeguard be reported as a false positives?
Francesco
Team
www.pianetasvapo.com
Sigaretta elettronica online al miglior prezzo



Il giorno gio 28 lug 2022 alle ore 11:43 Mathias Reker ⚡️ <
***@***.***> ha scritto:
