### ISSUE TITLE
Resolve the vulnerability but keep showing error on filepermissions

### ISSUE THREAD

**Issue by chon59** [MathiasReker/blmvuln#8]
Hi first thanks a lot it seems to have fixed the vulnerability but it keeps showing this message : 

```
The following filepermissions are insecure. They will be fixed by running the cleaning process:
themes/default/postcss.config.js
[...]
```
with a long list of files 

But when I launch the cleaning it keep showing this after it ran.

What can I do ?

Thanks

**Comment by MathiasReker** [comment]
Hello @chon59 

I guess your host has disabled the chmod function on your server.

I cannot reproduce the issue.
